language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - TYPO3_BRANCH=master COVERAGE=0

notifications:
  email:
#    - georg.ringer@gmail.com

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - sudo apt-get install parallel
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv news typo3conf/ext/

script:
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find . -wholename '*typo3conf/ext/news/Tests/Functional/*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; ./bin/phpunit --colors -c typo3conf/ext/news/Tests/Build/FunctionalTests.xml {}'
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3conf/ext/news/Tests/Build/UnitTests.xml typo3conf/ext/news/Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/news -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "